#!/usr/bin/env bash
# Departarr setup script
# Usage: bash scripts/setup.sh
set -euo pipefail

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

info()  { echo -e "${GREEN}[departarr]${NC} $*"; }
warn()  { echo -e "${YELLOW}[warn]${NC} $*"; }
error() { echo -e "${RED}[error]${NC} $*" >&2; exit 1; }

# ── 1. Check Docker ──────────────────────────────────────────────────────────
if ! command -v docker &>/dev/null; then
  error "Docker is not installed. Install it from https://docs.docker.com/get-docker/ and re-run this script."
fi

DOCKER_VERSION=$(docker --version 2>/dev/null || true)
info "Found $DOCKER_VERSION"

# Prefer 'docker compose' (v2 plugin); fall back to 'docker-compose' (v1 standalone)
if docker compose version &>/dev/null 2>&1; then
  COMPOSE="docker compose"
elif command -v docker-compose &>/dev/null; then
  COMPOSE="docker-compose"
else
  error "Docker Compose is not available. Install it from https://docs.docker.com/compose/install/"
fi

info "Using compose command: $COMPOSE"

# ── 2. Ensure data directory exists ─────────────────────────────────────────
mkdir -p ./data
info "Data directory: $(pwd)/data"

# ── 3. VAPID keys — auto-generated by the container on first boot ────────────
# The container generates VAPID keys automatically and stores them in
# ./data/config.json, so no manual generation is needed.
# This step only creates a .env file if the user wants to override values.
if [[ ! -f .env ]]; then
  info "No .env file found — the container will auto-generate all secrets on first boot."
  info "If you want to set optional env vars (AeroDataBox key, Google OAuth, etc.),"
  info "copy .env.example to .env and fill in your values."
else
  info "Found existing .env file — values will be passed to the container."
fi

# ── 4. Pull latest image ─────────────────────────────────────────────────────
info "Pulling latest image..."
$COMPOSE pull

# ── 5. Start container ───────────────────────────────────────────────────────
info "Starting Departarr..."
$COMPOSE up -d

# ── 6. Wait for the container to be healthy ──────────────────────────────────
info "Waiting for Departarr to start..."
for i in $(seq 1 20); do
  if curl -sf http://localhost:8080/api/health &>/dev/null; then
    break
  fi
  sleep 1
done

echo ""
echo -e "${GREEN}╔══════════════════════════════════════════════════╗${NC}"
echo -e "${GREEN}║        Departarr is running!                     ║${NC}"
echo -e "${GREEN}╠══════════════════════════════════════════════════╣${NC}"
echo -e "${GREEN}║  Local URL:   http://localhost:8080              ║${NC}"
echo -e "${GREEN}║  Data:        $(pwd)/data               ${NC}"
echo -e "${GREEN}╚══════════════════════════════════════════════════╝${NC}"
echo ""
echo "Next steps:"
echo "  1. Open http://localhost:8080 and create your account."
echo "  2. (Optional) Get a free AeroDataBox key at:"
echo "     https://aerodatabox.com → Settings → Flight Data"
echo "     Then paste it in Departarr → Settings → Data Sources."
echo "  3. (Optional) For push notifications and Google Calendar,"
echo "     expose Departarr via HTTPS — see SELF_HOSTING.md for options."
echo ""
echo "To view logs:    $COMPOSE logs -f"
echo "To stop:         $COMPOSE down"
echo "To update:       $COMPOSE pull && $COMPOSE up -d"
